# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.state.com:
  orderer3.state.com:
  orderer4.state.com:
  orderer5.state.com:

networks:
  drugledgerscript:

services:

  orderer2.state.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.state.com
    networks:
    - drugledgerscript
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/state.com/orderers/orderer2.state.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/state.com/orderers/orderer2.state.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.state.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.state.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.state.com
    networks:
    - drugledgerscript
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/state.com/orderers/orderer3.state.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/state.com/orderers/orderer3.state.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.state.com:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer4.state.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.state.com
    networks:
    - drugledgerscript
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/state.com/orderers/orderer4.state.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/state.com/orderers/orderer4.state.com/tls/:/var/hyperledger/orderer/tls
        - orderer4.state.com:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.state.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer5.state.com
    networks:
    - drugledgerscript
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/state.com/orderers/orderer5.state.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/state.com/orderers/orderer5.state.com/tls/:/var/hyperledger/orderer/tls
        - orderer5.state.com:/var/hyperledger/production/orderer
    ports:
    - 11050:7050
